# Veri Bilimi Eğitimi

## Grup Bazlı Analiz

Amaç:
  1. Veri setini farklı kırılımlara ayırarak grup bazlı analiz yapalım
  2. groupby yapısı ile özet istatistikler üretip sonuçları yorumlamak

Adımlar:
  1. Veri setini yüklemek
  2. Grup bazlı analiz için kullanılacak sütunları belirle
  3. Kategoriye göre temel analiz
  4. Şehre göre temel analiz
  5. Müşteri tipine göre temel analiz
  6. Ödeme türüne göre temel analiz
  7. Birden fazla sütun ile grup bazlı analiz

In [ ]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [ ]:
# 1. veri setini yükleyelim
# 2. grup bazlı analiz için kullanılacak sütunları belirle
df = pd.read_csv("e_ticaret_veri_seti_aykiri_degerler_duzenlendi.csv")
df.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ayi,siparis_gunu,haftanin_gunu
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,49.9,Kredi Kartı,Yeni,3.0,5.0,Hayır,0.220,443.68,2024,1,13,Saturday
1,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,49.9,Kapıda Ödeme,Yeni,3.0,5.0,Hayır,0.250,1023.80,2024,8,10,Saturday
2,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,39.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday
3,SIP100687,MUS1147,2025-08-09 08:42:00,Konya,İç Anadolu,Kozmetik,Nemlendirici,2,417.02,0.00,59.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.220,893.94,2025,8,9,Saturday
4,SIP100254,MUS1447,2024-07-30 09:06:00,Konya,İç Anadolu,Elektronik,Bluetooth Hoparlör,1,1327.75,0.05,29.9,Banka Kartı,Mevcut,4.0,5.0,Hayır,0.283,1291.26,2024,7,30,Tuesday

In [ ]:
# 3. kategoriye göre temel analiz
kategori_analizi = df.groupby("kategori").agg(
    {
        "toplam_tutar": ["count", "mean", "sum"],
        "birim_fiyat": "mean",
        "musteri_puani": "mean",
        "teslimat_gunu": "mean"
    }
).round(1)
kategori_analizi

           toplam_tutar                   birim_fiyat musteri_puani  \
                  count    mean       sum        mean          mean
kategori
Elektronik          140  1520.9  212930.3      1065.5           4.2
Ev Yaşam            184   773.6  142335.6       366.7           4.3
Kitap               223   511.5  114075.6       224.8           4.3
Kozmetik            200   737.6  147522.9       373.6           4.4
Ofis                162   290.4   47051.9       138.2           4.2
Spor                186  1018.7  189481.9       614.5           4.3

           teslimat_gunu
                    mean
kategori
Elektronik           3.3
Ev Yaşam             3.4
Kitap                3.4
Kozmetik             3.4
Ofis                 3.1
Spor                 3.2

In [ ]:
# 4. şehre göre temel analiz yapalım
sehir_analiz = df.groupby("sehir").agg(
    {
        "toplam_tutar": ["sum", "mean"],
        "teslimat_gunu": "mean",
        "musteri_puani": "mean"
    }
).round(1)
sehir_analiz

          toplam_tutar        teslimat_gunu musteri_puani
                   sum   mean          mean          mean
sehir
Adana          50353.3  799.3           3.5           4.3
Ankara         96721.1  780.0           3.1           4.2
Antalya        63712.8  740.8           3.5           4.3
Bursa          46782.8  698.3           3.5           4.2
Eskişehir      37550.0  834.4           3.2           4.2
Gaziantep      35240.3  719.2           3.4           4.3
Kayseri        24878.8  691.1           3.6           4.3
Kocaeli        21293.0  686.9           3.3           4.2
Konya          59424.3  771.7           3.3           4.4
Mersin         38043.9  827.0           3.5           4.2
Samsun         36263.5  805.9           3.3           4.4
Trabzon        30395.2  690.8           3.4           4.2
İstanbul      224020.6  848.6           3.3           4.4
İzmir          88718.5  751.9           3.1           4.2

In [ ]:
# 5. müşteri tipine göre temel analiz
musteri_tipi_analiz = df.groupby("musteri_tipi").agg(
    {
        "toplam_tutar": ["sum", "mean"],
        "teslimat_gunu": "mean",
        "musteri_puani": "mean"
    }
).round(1)
musteri_tipi_analiz

             toplam_tutar        teslimat_gunu musteri_puani
                      sum   mean          mean          mean
musteri_tipi
Mevcut           442921.1  793.8           3.3           4.3
VIP              107110.0  836.8           3.4           4.3
Yeni             303367.0  741.7           3.3           4.3

In [ ]:
# 6. ödeme türüne göre temel analiz
odeme_turu_analizi = df.groupby("odeme_turu").agg(
    {
        "toplam_tutar": ["sum", "mean"],
        "teslimat_gunu": "mean",
        "musteri_puani": "mean"
    }
).round(1)
odeme_turu_analizi

               toplam_tutar        teslimat_gunu musteri_puani
                        sum   mean          mean          mean
odeme_turu
Banka Kartı        143011.1  846.2           3.5           4.2
Dijital Cüzdan     129911.2  849.1           3.3           4.3
Havale/EFT          92894.5  836.9           3.1           4.2
Kapıda Ödeme        48113.2  609.0           3.2           4.4
Kredi Kartı        439468.2  753.8           3.3           4.3

In [ ]:
# 7. birden fazla sütun ile grup bazlı analiz
kategori_musteri_tipi_analizi = df.groupby(["kategori", "musteri_tipi"]).agg(
    {
        "toplam_tutar": ["mean", "sum"],
        "musteri_puani": "mean",
        "teslimat_gunu": "mean"
    }
).round(1)
kategori_musteri_tipi_analizi

                        toplam_tutar           musteri_puani teslimat_gunu
                                mean       sum          mean          mean
kategori   musteri_tipi
Elektronik Mevcut             1591.2  127297.1           4.3           3.4
           VIP                1364.6   28657.2           4.0           3.0
           Yeni               1451.1   63846.8           4.2           3.3
Ev Yaşam   Mevcut              792.2   76848.2           4.3           3.5
           VIP                 837.7   18428.6           4.3           3.5
           Yeni                710.0   47571.4           4.2           3.3
Kitap      Mevcut              478.0   54492.0           4.3           3.5
           VIP                 577.9   15604.2           4.1           3.6
           Yeni                527.8   45387.2           4.2           3.2
Kozmetik   Mevcut              720.1   82088.4           4.3           3.4
           VIP                 725.9   20325.0           4.5           3.8
           Yeni                786.4   47968.9           4.6           3.1
Ofis       Mevcut              273.5   20513.5           4.3           3.1
           VIP                 252.7    3538.3           4.1           2.6
           Yeni                310.7   23613.4           4.2           3.3
Spor       Mevcut              996.6   91689.4           4.3           3.2
           VIP                1264.1   22753.9           4.4           3.0
           Yeni               1006.8   82555.6           4.2           3.3